export EDITOR="/usr/bin/nvim"
export PATH=/usr/bin/:$PATH

# If bashrc file exists load it
if [ -f ~/.config/bash/bashrc ]; then . ~/.config/bash/bashrc; fi

# If running from tty1 start sway
if [ "$(tty)" = "/dev/tty1" ]; then
	exec sway
fi
