alias vim=nvim
alias ls='ls --color=auto -h'
alias ll='ls -l'
alias la='ls -lA'
alias ..='cd ..'
alias mkdir='mkdir -p'
alias df='df -h'
export GTK_THEME='Arc-Dark'
export EDITOR="/usr/bin/nvim"

# If running from tty1 start sway
if [ "$(tty)" = "/dev/tty1" ]; then
	exec sway
fi
